### ISSUE TITLE
部分在线瓦片加载报错

### ISSUE THREAD

**Issue by binfenshijie** [deyihu/maptalks-tileLayercollection#1]
![111111111111111111111111111](https://user-images.githubusercontent.com/13793642/45153506-d2bdc480-b206-11e8-8c43-ba51f1da3d59.png)

天地图Tdt-Normal。第一次setbaselayer可以，再次设置出现问题报错如上

<!DOCTYPE html>
<html>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>加载在线瓦片合集</title>
  <style type="text/css">
    html,body{margin:0px;height:100%;width:100%}
    .container{width:100%;height:100%}
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/maptalks@0.40.5/dist/maptalks.css">
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks@0.40.5/dist/maptalks.min.js"></script>
  <script type="text/javascript" src="js/maptalks-tileLayercollection.js"></script>

  <body>

    <div id="map" class="container"></div>

    <script>
        var map = new maptalks.Map('map', {
          center: [109.1748453547,21.4586700546],
          zoom: 13
        });

//-加载在线瓦片合集-//
      // horizonal one on bottom left
	  var id='helle-world-layer';
	  var names=[
          'Tdt-Normal','Tdt-Satellite','Tdt-Terrain',
          'Geoq-Colour','Geoq-Gray','Geoq-Midnightblue',
          'Google-Normal','Google-Satellite',
          'Amap-Normal','Amap-Satellite',
          'Tencent-Normal','Tencent-Satellite','Tencent-Terrain',
          'Osm-Normal','Osm-Bike','Osm-Transport','Osm-Humanitarian',
          'CartoDb-Light','CartoDb-Dark',
          'Mapbox-Streets','Mapbox-Dark','Mapbox-LightDark','Mapbox-Satellite','Mapbox-Light',
          'Mapbox-Emerald','Mapbox-White','Mapbox-Red','Mapbox-Outdoors','Mapbox-StreetsSatellite',
          'Mapbox-Comic','Mapbox-Building'
        ];
	  var tileLayers={};
     for(var i=0;i<names.length;i++){
            var name=names[i];
            var nameArr=name.split('-');
            var methodName='get'+nameArr[0]+'TileLayer';
            var style=nameArr[1];

            var baseLayers=maptalks.TileLayerCollection[methodName](id+i,{style:style});
            tileLayers[name]=baseLayers;
        }
	 map.setBaseLayer(tileLayers[names[0]]);
     var toolbar_test = new maptalks.control.Toolbar({
        'vertical' : true,
        'position' : { 'top' : 20, 'right' : 20 },
     //   'reverseMenu' : true,
        'items'     : [{
          item: 'offline-Amap',
          click : function () { 
			console.log('offline-Amap');
			 },
          children : [{
            item: 'Tdt-Normal',
            click : function () {
				debugger;
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tdt-Normal']);
			}
          }, {
            item: 'Tdt-Satellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tdt-Satellite']);
				}
          },{
            item: 'Tdt-Terrain',
            click : function () { 				
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tdt-Terrain']);
				}
          },{
            item: 'Geoq-Colour',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Geoq-Colour']);
				}
          },{
            item: 'Geoq-Gray',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Geoq-Gray']);
				}
          },{
            item: 'Geoq-Midnightblue',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Geoq-Midnightblue']);
				}
          },{
            item: 'Google-Normal',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Google-Normal']);
				}
          },{
            item: 'Google-Satellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Google-Satellite']);
				}
          },{
            item: 'Amap-Normal',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Amap-Normal']);
				}
          },{
            item: 'Amap-Satellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Amap-Satellite']);
				}
          },{
            item: 'Tencent-Normal',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tencent-Normal']);
				}
          },{
            item: 'Tencent-Satellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tencent-Satellite']);
				}
          },{
            item: 'Tencent-Terrain',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Tencent-Terrain']);
				}
          },{
            item: 'Osm-Normal',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Osm-Normal']);
				}
          },{
            item: 'Osm-Bike',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Osm-Bike']);
				}
          },{
            item: 'Osm-Transport',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Osm-Transport']);
				}
          },{
            item: 'Osm-Humanitarian',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Osm-Humanitarian']);
				}
          },{
            item: 'CartoDb-Light',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['CartoDb-Light']);
				}
          },{
            item: 'CartoDb-Dark',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['CartoDb-Dark']);
				}
          },{
            item: 'Mapbox-Streets',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Streets']);
				}
          },{
            item: 'Mapbox-Dark',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Dark']);
				}
          },{
            item: 'Mapbox-LightDark',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-LightDark']);
				}
          },{
            item: 'Mapbox-Satellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Satellite']);
				}
          },{
            item: 'Mapbox-Light',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Light']);
				}
          },{
            item: 'Mapbox-Emerald',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Emerald']);
				}
          },{
            item: 'Mapbox-White',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-White']);
				}
          },{
            item: 'Mapbox-Red',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Red']);
				}
          },{
            item: 'Mapbox-Outdoors',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Outdoors']);
				}
          },{
            item: 'Mapbox-StreetsSatellite',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-StreetsSatellite']);
				}
          },{
            item: 'Mapbox-Comic',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Comic']);
				}
          },{
            item: 'Mapbox-Building',
            click : function () {
				map.removeBaseLayer(map.getBaseLayer());
				map.setBaseLayer(tileLayers['Mapbox-Building']);
				}
          }]
        }]
      }).addTo(map);
    </script>
  </body>
</html>

**Comment by binfenshijie** [comment]
[maptalk_tete.txt](https://github.com/deyihu/maptalks-tileLayercollection/files/2356715/maptalk_tete.txt)
代码整理，望指正

**Comment by deyihu** [comment]
@binfenshijie  不好意思刚看到，我看了一下和你的代码无关，
我用
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/maptalks@0.39.0/dist/maptalks.min.js"></script>
这版本是可以的。
这个应该是maptalks的bug，我待会看看给maptalks提个issue  :bowtie:
